import ExchangeLib
print("This is money Exchange program")
money = float(input("Enter your money : "))
print(f"{"-"*10}Currency Choice{"-"*10}")
print(" - 1. Thai - bath")
print(" - 2. US - Dollar")
print(" - 3. Euro")
print(" - 4. japan - Yen")
print(" - 5. Chinese - Yuan")
print(" - 6. Russia - Ruble")
print("-"*35)
choice1 = int(input("Which currency is your money : "))
choice2 = int(input("Which currency you want to exchange to : "))
A = ExchangeLib.trade(money)
A.exchange(choice1,choice2)